-- Schema for the AI PR Reviewer history store (Supabase / Postgres).
--
-- Append-only: every workflow run inserts exactly one row into pr_review_runs
-- and one row per surviving finding into pr_review_findings. Nothing is ever
-- updated or deleted by the action, so this doubles as an audit log.
--
-- Apply with:  psql "$DATABASE_URL" -f src/history/schema.sql
-- or paste into the Supabase dashboard SQL editor.

create table if not exists pr_review_runs (
  -- Generated by the action (crypto.randomUUID) so findings can reference it
  -- without a second round trip to read back a serial id.
  id                    uuid primary key,
  created_at            timestamptz  not null default now(),

  -- Where
  repo                  text         not null,
  pr_number             integer      not null,
  head_sha              text         not null,
  base_branch           text,
  head_branch           text,
  pr_title              text,
  pr_author             text,

  -- How it was reviewed
  provider              text         not null,
  model                 text         not null,
  categories            text[]       not null default '{}',
  is_incremental        boolean      not null default false,
  incremental_base_sha  text,
  -- True when the run short-circuited on an already-reviewed SHA and replayed
  -- stored findings instead of calling the LLM.
  cached                boolean      not null default false,

  -- Scale of the change
  changed_files_count   integer      not null default 0,
  reviewed_files_count  integer      not null default 0,
  ignored_files_count   integer      not null default 0,

  -- Cost and effort
  input_tokens          integer      not null default 0,
  output_tokens         integer      not null default 0,
  total_tokens          integer      not null default 0,
  api_calls             integer      not null default 0,
  -- Null when the model has no entry in the local rate table.
  estimated_cost_usd    numeric(10, 4),
  duration_ms           integer      not null default 0,

  -- Outcome
  findings_count        integer      not null default 0,
  critical_count        integer      not null default 0,
  warning_count         integer      not null default 0,
  suggestion_count      integer      not null default 0,
  -- Category ids whose specialist crashed; empty when all succeeded.
  failed_specialists    text[]       not null default '{}',
  -- True when the judge output could not be parsed and findings are unverified.
  judge_unverified      boolean      not null default false,

  -- Traceability back to the Actions run that produced this row
  github_run_id         text,
  github_run_attempt    integer,
  github_actor          text,
  github_workflow       text
);

create table if not exists pr_review_findings (
  id            uuid primary key,
  run_id        uuid         not null references pr_review_runs (id) on delete cascade,
  created_at    timestamptz  not null default now(),

  -- Denormalized from the parent run so the common "all criticals in repo X"
  -- query needs no join. Append-only data, so these can never drift.
  repo          text         not null,
  pr_number     integer      not null,
  head_sha      text         not null,

  -- Stable id across runs (category|file|message-headline). Lets you track a
  -- single bug's lifetime: first seen, how many runs it survived, when it went away.
  fingerprint   text         not null,
  category      text         not null,
  severity      text         not null check (severity in ('critical', 'warning', 'suggestion')),
  confidence    text         not null check (confidence in ('high', 'medium', 'low')),
  file          text         not null,
  line          integer,
  code_snippet  text,
  message       text         not null
);

create index if not exists pr_review_runs_repo_pr_idx
  on pr_review_runs (repo, pr_number, created_at desc);
create index if not exists pr_review_runs_created_at_idx
  on pr_review_runs (created_at desc);
create index if not exists pr_review_runs_head_sha_idx
  on pr_review_runs (head_sha);

create index if not exists pr_review_findings_run_idx
  on pr_review_findings (run_id);
create index if not exists pr_review_findings_repo_pr_idx
  on pr_review_findings (repo, pr_number, created_at desc);
create index if not exists pr_review_findings_fingerprint_idx
  on pr_review_findings (repo, fingerprint, created_at desc);
create index if not exists pr_review_findings_severity_idx
  on pr_review_findings (severity, created_at desc);

-- Row Level Security.
--
-- The action authenticates with a secret key (sb_secret_... or the legacy
-- service_role key), which bypasses RLS. Enabling RLS with no permissive policy
-- therefore keeps the action working while blocking anon/publishable keys from
-- reading your review history through the public API.
alter table pr_review_runs     enable row level security;
alter table pr_review_findings enable row level security;
